# .github/workflows/python-test.yml

name: Chatbot CI/CD Pipeline

on:
  push:
    branches:
      - main
      - testing
      - dev
  pull_request:
    branches:
      - main
      - testing
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.3"]

    env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: sqlite:///./test.db


    steps:
    - uses: actions/checkout@v4
    
    - name: Create venv
      run: |
        python3.12 -m venv "$VENV_DIR"
        source .venv/bin/activate

    - name: Ensure Scripts are executable
      run: |
        chmod 700 scripts/chmodAllScripts.sh
        ./scripts/chmodAllScripts.sh

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        ./scripts/InstallDependencies.sh

    - name: Start FastAPI Server
      run: | 
        ./scripts/StartServer.sh

    - name: Run tests
      run: |
        ./scripts/RunTests.sh
    
    - name: Stop FastAPI Server
      run: |
        ./scripts/StopServer.sh
      if: always()
      
      

      