# .github/workflows/python-test.yml

name: Chatbot CI/CD Pipeline

on:
  push:
    branches:
      - main
      - testing
      - dev
  pull_request:
    branches:
      - main
      - testing
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.3"]

    env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/backend_requirements.txt
        pip install google-genai google-api-core python-dotenv pytest groq
        pip install fastapi uvicorn "python-multipart[standard]"

    - name: Start FastAPI Server
      run: | 
        uvicorn src.server:app --host 0.0.0.0 --port 8000 &
        echo $! > uvicorn_pid.txt
        sleep 3

    - name: Run tests
      run: |
        python -m pytest tests/
    
    - name: Stop FastAPI Server
      run: |
        kill $(cat uvicorn_pid.txt)
        rm uvicorn_pid.txt
      if: always()
      
      

      